language: node_js
node_js:
- node
script:
- npm run-script oneOff
deploy:
  provider: npm
  email: jameswilddev@outlook.com
  api_key:
    secure: w9k5aN23vvBo372NBO2pv690q30y58mk11FUAU8+ArltjY+3mwqrhe880OQf5nLCWoEN++5M9Aq66RIq5Nk2feUzCOPXAw0QYmhoT0hUVRp7dFA5tcv6WxK7jIh1WqMvNoL0s2YGMEoYiSQJWHKlKKKNkFIWQ9BZZCjt23kbRbPvfx4wCOMfhmZOj5dYAVnVNlUNTTzS89retw19F7vTIeioIrKR6lfLlLuxjkMb8+66alDixPshNfZBYqRXLSQQWyTBX5MX+PJFxUpu7Jqp3BLgc3fhYMZ9zKzP/iYA10lG4FWqueyZjYQ4WO00myDTkh7sklhYhCeDhAwXIG5InS0qjv5Tist3ZxFAaVXZE1dO2sBFCsIViT10V/6OESQJn+Ucj/okEqD6QnwvKGvjWG1JFuDHDeSd0BlIPKPGhHO0+KRQ55TMsM/t5Opj9h4a/uqaAuPuelTcIz4gvuJsjugSxEZSsOIBkp4emm6J9bQOdKSlafWejSwefISE4gQcIRT1B5PPphSEgtTFlfuyFQzijRBc3EUcQVQ4mP00J8gujT7n37ZgMCAbK1rSbqo2sqSCbX7SyimTdgSM5+CFLeJVCvOyj0Z6ckdNbHB/nHRImN/cFs1OaXKK4zwmIQjSo0hW9N8L+g3RPPXm2A2kVfhmc2Pxs03chWl74rIr21g=
  on:
    tags: true
    repo: jameswilddev/HAgAl
    branch: master
